apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: jfrog-argo
images:
- newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/spring-boot-repo
  newTag: v3
- name: example
  newName: 472496548172.dkr.ecr.us-east-2.amazonaws.com/upgradetest
  newTag: kustomize
